language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
before_script:
  - wget https://phar.phpunit.de/phpunit-5.7.phar
  - chmod +x phpunit-5.7.phar
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then mv phpunit-5.7.phar /usr/local/bin/phpunit ; fi
script:
  - phpunit tests/ChartjsChartTest.php